### ISSUE TITLE
normalling VCO1 to VCO2 cv and vice versa

### ISSUE THREAD

**Issue by av500** [forestcaver/Benjolin#1]
hi there, 

why not hook it up like a standalone Benjolin and normal VCO1 TRI to VCO2 CV in and VCO2 TRI to VCO1 CV in? it make it much more useful without the need for patching.

**Comment by forestcaver** [comment]
Thanks Vlad - I didnt know the standalone one did that ! It took me a fair bit of searching to find schematics that showed it.... All the schematics I’d found on electro-music and for modular benjolins (euro, 4u and 5u) didnt have that normalling so it didnt cross my mind..... and I didnt think
about it !

I guess with the attenuation you don’t lose anything at all by doing that normalling..... it’s a good idea - I’ll add it to the next revision. I’ll also increase the gain after the filter when I revise it.

I’ll try to add it and test the board before christmas.

Thanks.

**Comment by forestcaver** [comment]
Added the above, along with normalling to filter cv input (still needs testing)

**Comment by av500** [comment]
btw, would be nice to have the schematics as a PDF in git as well, not everybody has Eagle on their phone :)

**Comment by forestcaver** [comment]
Schematic uploaded :-)

**Comment by forestcaver** [comment]
Fixed in v1.6
