### ISSUE TITLE
IC Orientation

### ISSUE THREAD

**Issue by Microfi** [forestcaver/Benjolin#4]
Thank you for this wonderful project, forestcaver!

I just received my PCB's and I was wondering what the orientation of the IC's is.
For IC1 this is indicated on the silkscreen, but I don't see this same indication for the other IC's.

**Comment by forestcaver** [comment]
Have a look in eagle (download the free version). All the design files are there. Orientation is seen in tdocu and tplace layers. You can generate gerbers with those layers in the silkscreen if you wanted.

**Comment by Microfi** [comment]
> Have a look in eagle (download the free version). All the design files are there. Orientation is seen in tdocu and tplace layers. You can generate gerbers with those layers in the silkscreen if you wanted.

Those layers indeed contained the information. Thanks a lot for your help!

**Comment by forestcaver** [comment]
No problem - enjoy.
