### ISSUE TITLE
sourcing parts from bom

### ISSUE THREAD

**Issue by langolierz** [forestcaver/Benjolin#5]
hi @forestcaver thanks a lot for sharing this !

i am currently sourcing parts for this build and there are a few things that confused me (this is my first time looking for smd parts though so might just be me) , thought i would share them here anyway. maybe they will help someone. i am looking for parts on mouser.

- it wasnt that obvious what the `PANASONIC_A` footprint meant ... i ended up grabbing some that had 4mm diameter
- i couldnt really figure out the difference between the `POT_USVERTICAL_PS` and `POT_USVERTICAL_NARROW`. (can see on the pcb that the holes are smaller on narrow, but couldnt find a part that explicitly says 'narrow') is there a reason why you didnt just use a footprint that would fit both ? (oh and maybe it should say that the pots are linear ? )
-  i couldnt find a 1n4004 in D-SMA , went for this BYG21M-E3 instead
- (probably this is well known but) SSM2164S is discontinued. you can get the replacement V2164M from places like thonk (although not from mouser )
- mouser doesnt stock lm79l09 or any -9v linear regulators. i will have to get this from ebay or something i guess..
- seems will have to source sub-mini switches from thonk also, cant find them on mouser (or tayda)

**Comment by forestcaver** [comment]
Sorry to hear about your part sourcing problems

panasonic A, B,C and D are standard footprint sizes for electrolytics.

The two pot footprints are for tall trimmers and alpha/alps pots
The part value is in the eagle files,

I just checked this morning and mouser has several hundred thousand of those diodes so they’re not uncommon. Just check the response time of your chosen substitute - 1n409x are chosen for a reason...

2164 - I use v2164 as I have loads but ssi and alfa also make them. You can probably omit the protection diode if you use ssi (and maybe alfa - havent checked) but not if you use coolaudio.

Mouser doesnt stock everything all the time. There are other places to get parts eg voltage regulators.

Mouser does sell sub mini toggle switches, however. (But they’re cheaper elsewhere)

Sometimes, with diy projects, you wont find everything at mouser and will sometimes need to source parts yourself from other suppliers.
