### ISSUE TITLE
Potentiometer specifications

### ISSUE THREAD

**Issue by eraxeg** [forestcaver/Benjolin#6]
Can you provide some details about the potentiometers? 

What is the difference between ALPS_POT_NARROW and ALPS_POT_VERTICAL_PS?

Are they linear or logarithmic?

What is a good height?

Thanks,
Erik

**Comment by forestcaver** [comment]
All pots are linear
Narrow are talk trimmers eh song heui
Other pots - I use thonk alphas which are about the same height as thonkiconns
