### ISSUE TITLE
4021D IC references

### ISSUE THREAD

**Issue by Klodifokan** [forestcaver/Benjolin#7]
Hi,

I'd like to build a Benjolin but I can't find a 4021D IC.
Do you have a reference from Mouser or another website please?

Thanks for your help.

**Comment by forestcaver** [comment]
There are thousands on Mouser - just checked. I’m closing this as it’s not an issue with the module.
I’m sorry - I can’t offer any further build or parts sourcing support.

**Comment by Klodifokan** [comment]
Thanks
this is what I call help

**Comment by forestcaver** [comment]
This one will work....

https://www.mouser.co.uk/ProductDetail/595-CD4021BM96

**Comment by Klodifokan** [comment]
Et bien voilà
Thanks
