### ISSUE TITLE
Pot footprint and panel hole

### ISSUE THREAD

**Issue by jamesbondsai** [forestcaver/Benjolin#8]
Small note while building. I use alpha pots and Song Huei tall trimmers. I noticed that the holes for the ground legs on the song huei footprint are way too small to fit any ground legs. (I just cut them off in my case). 
I also noticed that the panel hole for R60 (alpha pot) has a diameter of 6.5mm (tall trimmer size) instead of 7.5 on the other alpha pot holes. Will drill it out, no problem. But I thought I'd let you know :). 

Thanks a lot for your work, on the benjolin and other modules!

**Comment by forestcaver** [comment]
Thanks - I didnt have any issues with the tall trimmers and I dont believe others have.... sometimes the board manufacturer you choose doesnt implement the milling correctly (have a look at the board file - there are milling slots for the tall trimmers.... Have a look at the gerbers in a gerber viewer - there are plated slots clearly shown for the tall trimmers....

R60 - yeah - should be slightly larger !!! Thanks ! (But I’m not going to change it and reorder panels to test just yet :-) ) I have plans to update the benjolin and have made quite a few changes but not got around to ordering test pcbs yet as I’m occasionally making a few more changes.... I’ll update it when I get around to finalising some ideas....
